name: Next.js CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:

    runs-on: self-hosted

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Check Environment
      shell: powershell
      run: |
        node -v
        npm -v
        pnpm -v


    - name: Deploy Code to IIS Folder
      shell: powershell
      run: |
        $source = "$env:GITHUB_WORKSPACE"
        $destination = "C:\inetpub\wwwroot\Node\reactjs-projects-main"

        robocopy $source $destination /MIR /XD node_modules .next .git

        if ($LASTEXITCODE -le 7) {
          exit 0
        }
        else {
          exit $LASTEXITCODE
        }


    - name: Install Dependencies
      shell: powershell
      working-directory: C:\inetpub\wwwroot\Node\reactjs-projects-main
      run: |
        pnpm install


    - name: Build Next.js Application
      shell: powershell
      working-directory: C:\inetpub\wwwroot\Node\reactjs-projects-main
      run: |
        pnpm build


    - name: Restart PM2 Application
      shell: powershell
      working-directory: C:\inetpub\wwwroot\Node\reactjs-projects-main
      run: |
        pm2 reload react-nextjs
        pm2 save


    - name: Restart IIS Application Pool
      shell: powershell
      run: |
        Import-Module WebAdministration
        Restart-WebAppPool -Name "NodeReact"
