name: Next.js CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:

    runs-on: self-hosted

    steps:

    - name: Checkout code
      uses: actions/checkout@v4


    - name: Check Node Version
      shell: powershell
      run: |
        node -v
        npm -v
        pnpm -v


    - name: Install dependencies
      shell: powershell
      run: |
        pnpm install


    - name: Build Next.js Application
      shell: powershell
      run: |
        pnpm build


    - name: Restart PM2 Application
      shell: powershell
      run: |
        pm2 restart react-nextjs
        pm2 save
